AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CloudWatch Log Monitor
  
  Serverless function to monitor CloudWatch Logs for error patterns and send notifications.

Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    Runtime: python3.12
    Architectures:
      - x86_64

Parameters:
  MonitoredLogGroupPattern:
    Type: String
    Default: "*"
    Description: "Pattern for log groups to monitor (e.g., '/aws/lambda/*')"
  
  AllowedS3Buckets:
    Type: CommaDelimitedList
    Default: "*"
    Description: "Comma-separated list of S3 bucket names for config (use '*' for all)"
  
  AllowedSNSTopics:
    Type: CommaDelimitedList
    Default: "*"
    Description: "Comma-separated list of SNS topic ARNs for notifications (use '*' for all)"

Conditions:
  UseAllS3Buckets: !Equals [!Join ["", !Ref AllowedS3Buckets], "*"]
  UseAllSNSTopics: !Equals [!Join ["", !Ref AllowedSNSTopics], "*"]

Resources:
  LogMonitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src.lambda_function.lambda_handler
      Description: Monitors CloudWatch Logs for errors
      Environment:
        Variables:
          CONFIG_SOURCE: ENV
          # STREAM_CONFIG: ... (Set via parameter or console)
          # SSM_PARAMETER_NAME: ...
          # S3_BUCKET: ...
          # S3_KEY: ...
      Policies:
        - Statement:
           - Sid: CloudWatchLogsAccess
            Effect: Allow
            Action:
              - logs:GetLogEvents
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${MonitoredLogGroupPattern}:log-stream:*"
          - Sid: SSMAccess
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParametersByPath
            Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"
          - Sid: S3Access
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: !If
              - UseAllS3Buckets
              - "arn:aws:s3:::*/*"
              - !Sub
                - "arn:aws:s3:::${BucketList}/*"
                - BucketList: !Join [",arn:aws:s3:::", !Ref AllowedS3Buckets]
          - Sid: SNSAccess
            Effect: Allow
            Action:
              - sns:Publish
            Resource: !If
              - UseAllSNSTopics
              - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:*"
              - !Ref AllowedSNSTopics

  # Example Log Group to monitor (Optional, for demo purposes)
  # In production, you would attach the subscription filter to existing log groups.
  DemoLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/demo-app
      RetentionInDays: 7

  # Subscription Filter
  LogSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      LogGroupName: !Ref DemoLogGroup
      FilterPattern: "" # Empty pattern to send all logs to Lambda for processing
      DestinationArn: !GetAtt LogMonitorFunction.Arn
      RoleArn: !GetAtt SubscriptionFilterRole.Arn

  # Role for CloudWatch Logs to invoke Lambda
  SubscriptionFilterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: logs.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt LogMonitorFunction.Arn

  # Permission for CloudWatch Logs to invoke Lambda (Resource-based policy)
  # This is often needed instead of or in addition to the Role depending on setup
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LogMonitorFunction
      Principal: logs.amazonaws.com
      SourceArn: !GetAtt DemoLogGroup.Arn

Outputs:
  LogMonitorFunctionArn:
    Description: "Log Monitor Lambda Function ARN"
    Value: !GetAtt LogMonitorFunction.Arn
  LogMonitorFunctionIamRole:
    Description: "Implicit IAM Role created for Log Monitor function"
    Value: !GetAtt LogMonitorFunctionRole.Arn
